import { GdwebDesignReference } from './gdweb-design-search.js';
import { GdwebSamplingImage } from './gdweb-sampling-images.js';

export function buildDesignSpecContract(
  reference: GdwebDesignReference,
  samplingImages: GdwebSamplingImage[]
): string {
  const { design, images } = reference;
  const sourceEvidence = images
    .map(image => `${image.kind}=${image.width}x${image.height}`)
    .join(', ');
  const preparedEvidence = samplingImages.map(image => {
    const colors = image.representativeColors
      .map(color => `${color.hex} ${formatPercent(color.coverage)}`)
      .join(', ');
    return [
      `- ${image.sourceKind} part ${image.part}/${image.totalParts}`,
      `  - source: ${image.sourceWidth}x${image.sourceHeight}px at ${image.sourceUrl}`,
      `  - prepared canvas: ${image.preparedCanvasWidth}x${image.preparedCanvasHeight}px`,
      `  - scale: x=${formatNumber(image.scaleX)}, y=${formatNumber(image.scaleY)}`,
      `  - attached crop in prepared coordinates: x=${image.cropLeft}, y=${image.cropTop}, width=${image.width}, height=${image.height}`,
      `  - mapped source crop: x=${image.sourceCropLeft}, y=${image.sourceCropTop}, width=${image.sourceCropWidth}, height=${image.sourceCropHeight}`,
      `  - measured representative palette: ${colors || 'unavailable'}`,
    ].join('\n');
  });

  return [
    '# GDWEB Reconstruction Specification Contract',
    '',
    '- Schema: secret-mcp/design-index/v2',
    `- Reference ID: gdweb-${design.strNo}`,
    `- Title: ${design.title}`,
    `- GDWEB URL: ${design.gdwebUrl}`,
    `- Registered date: ${design.registeredDate}`,
    `- Award: ${design.award || 'N/A'}`,
    `- Concept: ${design.concept || 'N/A'}`,
    `- GDWEB primary color metadata: ${design.primaryColor || 'N/A'}`,
    `- Production company: ${design.productionCompany || 'N/A'}`,
    `- Original evidence: ${sourceEvidence || 'unavailable'}`,
    '',
    '## Prepared Evidence Coordinate Map',
    '',
    ...preparedEvidence,
    '',
    'The measured representative palette is produced from downsampled screenshot pixels after JPEG normalization. It is objective screenshot evidence, but it is not proof of the original CSS token. Treat a sampled value as MEASURED and a proposed CSS token as INFERRED unless metadata confirms it.',
    '',
    '## Mandatory Next Action',
    '',
    `Inspect every attached evidence image and write one complete DESIGN_INDEX_gdweb-${design.strNo}.md document in the user's language.`,
    'The output is one artwork-specific document. Inside that document, inventory every page or route visible in the evidence and write a separate, complete specification for each page.',
    'The output-token budget belongs to this one work and is intentionally sized for multi-page evidence. Do not shorten, merge, or omit page subsections to save tokens.',
    'When multiple pages are visible, repeat every page-specific canvas, geometry, component, state, responsive, accessibility, asset, and acceptance requirement for each page.',
    'Do not combine this reference with another artwork. Do not produce a mood board, a brief summary, or a generic style guide.',
    '',
    '## Evidence and Measurement Rules',
    '',
    '- Prefix every material claim or table row with MEASURED, OBSERVED, INFERRED, or UNKNOWN.',
    '- MEASURED means derived from the supplied pixel coordinate map or sampled palette.',
    '- OBSERVED means directly visible in an attached GDWEB screenshot or supplied metadata but not numerically measured.',
    '- INFERRED means a concrete implementation decision needed to reproduce the evidence.',
    '- UNKNOWN means the static evidence does not reveal the value or behavior. Never state UNKNOWN behavior as fact.',
    '- Every geometry value must have a concrete number and unit. Prefer px for screenshot geometry, rem for an implementation equivalent, percentages for fluid ratios, and ms for motion.',
    '- When exact source CSS cannot be known, provide one recommended implementation value, its evidence basis, confidence HIGH/MEDIUM/LOW, and a visual QA tolerance. Do not provide only a broad range.',
    '- Measure attached crops in their prepared coordinate space. Use crop offsets and scale values above when mapping a point back to the full prepared canvas or original source image.',
    '- Tile overlap is evidence duplication, not repeated page content. Deduplicate sections by their prepared y coordinates.',
    '- A long scrolling screenshot is one page with many sections. Split it into multiple pages only when the evidence clearly shows distinct routes, screens, or page canvases.',
    '- If a collage contains multiple route screenshots, identify each route as a separate page and state the crop that supports it.',
    '- Preserve visible hierarchy and relationships. Adapt copyrighted copy and brand assets unless the user owns or authorizes them.',
    '- Treat desktop and mobile evidence as separate primary evidence. Explain every responsive transformation between them.',
    '- Vague adjectives such as large, modern, clean, spacious, or dynamic are invalid unless followed by measurable values.',
    '',
    '## Required Document Structure',
    '',
    '### 1. Reconstruction Goal and Scope',
    '- Reference identity, fidelity target, supported pages/routes, target viewports, framework-independent requirements, and explicit non-goals.',
    '- State whether the evidence represents one long page, multiple pages, or an ambiguous collage.',
    '',
    '### 2. Evidence Inventory and Coordinate System',
    '- Create one row per attached image with evidence ID, kind, part, source dimensions, prepared dimensions, crop rectangle, source-mapped rectangle, scale, visible page/section range, and limitations.',
    '- Define the canonical x/y origin and explain how overlapping tiles were deduplicated.',
    '- Map every later measurement to an evidence ID and coordinate or visible region.',
    '',
    '### 3. Site Map and Page/Route Inventory',
    '- List every directly visible page or route before describing components.',
    '- Required columns: Page ID, route/name, page purpose, supporting evidence IDs, shared shell variant, desktop availability, mobile availability, and confidence.',
    '- Do not invent unseen routes. Put likely but unseen routes in UNKNOWN rather than the implementation scope.',
    '- Identify the default page and the navigation item active on each page.',
    '',
    '### 4. Shared Application Shell',
    '- Specify viewport background, site max-width behavior, shared container widths, global gutters, page chrome, announcement bars, overlays, cookie UI, and stacking contexts.',
    '- Separate global primitives from page-specific composition.',
    '',
    '### 5. Navigation and Header Specification',
    '- This section is mandatory even when the header appears simple.',
    '- Provide a desktop navigation geometry table with: total header height, utility-bar height, content width, left/right padding, logo x/y/width/height, menu start x, item width or horizontal padding, item gap, baseline, icon size, action area width, border, background, position mode, and z-index.',
    '- Provide a mobile navigation geometry table with: bar height, side padding, logo bounds, menu-control bounds, touch target, open-panel origin, panel width/height, row height, indentation, divider, overlay, close behavior, and scroll locking.',
    '- List every visible navigation item in order and map it to a route or UNKNOWN target.',
    '- Define default, hover, focus-visible, pressed, active, disabled, scrolled, menu-open, and submenu-open states with exact color, border, opacity, and timing values.',
    '- State whether the header is static, sticky, fixed, transparent-over-hero, or transformed after scrolling. Mark screenshot-invisible transitions INFERRED or UNKNOWN.',
    '',
    '### 6. Page-by-Page Specifications',
    '- Create one `Page P-XX: <name>` subsection for every page in the route inventory.',
    '- Never replace page subsections with one global section list.',
    '- Never compress a multi-page work into one representative page, even when pages share the same shell or components.',
    '- Each page subsection must contain all of the following:',
    '  1. Route, purpose, entry points, shared shell variant, active navigation state, and supporting evidence.',
    '  2. Desktop canvas model: reference viewport, full page height, content max-width, gutters, columns, and page background.',
    '  3. Mobile canvas model: reference viewport, full page height if visible, side padding, stacking order, and overflow.',
    '  4. Ordered section geometry table from header to footer.',
    '  5. Detailed section specifications for every table row.',
    '  6. Page-specific components, data, states, interactions, responsive transitions, accessibility, assets, and acceptance checks.',
    '',
    'For each page, the ordered section geometry table must include:',
    '',
    '| Field | Required value |',
    '| --- | --- |',
    '| Section ID | Stable page-scoped ID such as P01-S03 |',
    '| Evidence | Image ID and x/y region |',
    '| Bounds | x, y, width, height in evidence pixels |',
    '| Semantic role | header, hero, nav, main, section, aside, footer, dialog, etc. |',
    '| Container | full bleed or max-width plus exact width and gutters |',
    '| Layout | block, flex, grid, absolute, sticky, fixed; include columns/tracks |',
    '| Spacing | outer margin, section padding, child gap, row gap, column gap |',
    '| Alignment | main axis, cross axis, text alignment, baseline behavior |',
    '| Surface | exact color/gradient/image, border, radius, shadow, opacity |',
    '| Content | visible text roles, controls, media, repeated item count |',
    '| Responsive | desktop-to-mobile transformation and breakpoint |',
    '| Evidence level | MEASURED, OBSERVED, INFERRED, or UNKNOWN plus confidence |',
    '',
    '### 7. Section and Layout Deep Dives',
    '- For every page section, provide the DOM hierarchy and exact CSS layout model.',
    '- Specify grid templates, flex properties, min/max widths, intrinsic sizing, aspect ratios, padding, gaps, alignment, wrapping, overflow, clipping, sticky offsets, absolute anchors, transforms, and z-index relationships.',
    '- Record desktop, tablet, and mobile values separately. Include a small CSS-ready implementation sketch for geometry that would otherwise be ambiguous.',
    '- For repeated cards or rows, specify item dimensions, count per row, minmax rule, gap, image ratio, text limits, and incomplete-row alignment.',
    '',
    '### 8. Component Abstraction',
    '- Provide a complete component tree rooted at AppShell and grouped by page.',
    '- For every component define responsibility, reusable boundary, props with types, variants, slots, local/shared state, events, data dependencies, loading, empty, error, disabled, and accessibility states.',
    '- Map every component back to page and section IDs.',
    '- Define shared navigation/footer once, then document page-specific active state or variants by reference.',
    '',
    '### 9. Design Tokens and Exact Color Specification',
    '- Provide CSS-ready token tables and a `:root` custom-property block.',
    '- Color rows require: stable token name, HEX, RGB, HSL, alpha, role, page/section usage, sampled evidence ID/coordinate or metadata source, evidence level, confidence, and allowed visual-diff tolerance.',
    '- Include background, surface, text, muted text, border, primary, secondary, accent, success, warning, danger, overlay, focus ring, hover, pressed, and disabled colors when present.',
    '- Use the measured palettes above as evidence, but distinguish photographic colors from UI surface/token colors.',
    '- Tokenize spacing, dimensions, radii, borders, shadows, opacity, z-index, breakpoints, container widths, icon sizes, and motion durations/easings with exact values.',
    '- Provide a spacing scale and identify every exception that does not fit it.',
    '',
    '### 10. Typography Matrix',
    '- Define family/fallback, source strategy, size px/rem, weight, line height px/unitless, letter spacing, casing, decoration, alignment, max width, wrap/truncation, and responsive value for every text role.',
    '- Include navigation labels, utility text, hero eyebrow/title/body, section headings, card titles/body/meta, controls, captions, form labels/errors, and footer text as applicable.',
    '',
    '### 11. Asset and Icon Manifest',
    '- Enumerate logos, photos, illustrations, icons, video, textures, charts, and decorative media per page.',
    '- For each asset specify page/section, role, evidence crop, displayed width/height, source aspect ratio, crop, focal point, object-fit/object-position, responsive treatment, loading priority, format, alt behavior, and replacement strategy.',
    '- Name familiar UI icons by library equivalent when identifiable; otherwise describe exact stroke/fill, bounds, and optical alignment.',
    '',
    '### 12. Responsive Behavior Matrix',
    '- Use columns for at least 1440, 1280, 1024, 768, 390, and 360 CSS px, unless evidence supports different canonical widths.',
    '- For every page and major component document container width, gutters, columns, order, visibility, navigation mode, type size, spacing, image crop, and touch target at each width.',
    '- Define breakpoint rules as behavioral transitions, not only numbers.',
    '- Mark values without direct mobile evidence INFERRED and give the reason.',
    '',
    '### 13. Interaction and Motion State Matrix',
    '- Cover links, navigation, buttons, menus, tabs, accordions, carousels, forms, modals, cards, media, hover, focus-visible, pressed, selected, disabled, loading, error, and success states.',
    '- For each state define trigger, visual delta, exact colors/opacity/transform, duration, easing, focus behavior, keyboard behavior, and reduced-motion alternative.',
    '- Screenshot-invisible behavior must be INFERRED or UNKNOWN.',
    '',
    '### 14. Accessibility Contract',
    '- Define page landmarks, heading order per page, skip link, keyboard and focus order, focus ring tokens, labels, alt text, live regions, error association, contrast targets, reduced motion, zoom/reflow, and minimum touch targets.',
    '- Navigation must include menu-button semantics, expanded state, focus containment/restoration, Escape handling, and active-page announcement where applicable.',
    '',
    '### 15. Data and Content Model',
    '- Define page-specific data entities, fields, cardinality, optional values, ordering, formatting, localization, loading/empty/error content, and sample fixture shapes.',
    '- Separate evidence copy from replaceable placeholder copy.',
    '',
    '### 16. Frontend Architecture',
    '- Specify routes, layouts, recommended directory structure, page modules, shared component modules, styling strategy, token files, asset organization, data models, state ownership, server/client boundaries, and third-party library responsibilities.',
    '- Keep framework choices separate from reconstruction requirements.',
    '',
    '### 17. Implementation Task Graph',
    '- Produce ordered task IDs with dependencies, inputs, outputs, affected page/section/component IDs, completion criteria, and parallelizable groups.',
    '- Include measurement setup, tokens, shared shell, navigation, page-by-page builds, responsive work, interactions, accessibility, visual QA, and performance.',
    '',
    '### 18. Page-Specific Acceptance Criteria',
    '- Create a separate acceptance checklist for every page.',
    '- Include screenshot comparison viewports, section bounds, container alignment, header/navigation geometry, color difference, typography metrics, overflow, text fitting, assets, keyboard, responsive state, and performance.',
    '- Default tolerance guidance: geometry within 4px for major edges, spacing within 2px for repeated rhythm, color deltaE <= 3 for flat UI colors, and no horizontal overflow. Override only with a stated reason.',
    '',
    '### 19. Uncertainties and Decisions',
    '- List every UNKNOWN item by page/section/component.',
    '- Record the concrete implementation decision selected in its place, alternatives rejected, confidence, and what additional evidence would resolve it.',
    '',
    '## Completion Gate',
    '',
    'The document is incomplete if it lacks a page/route inventory, a separate full specification for every visible page, a navigation geometry/state contract, evidence-linked pixel measurements, exact color formats, responsive matrices, component contracts, or page-specific acceptance criteria.',
    'Another LLM must be able to implement the artwork page by page from this document alone without reopening GDWEB and without inventing missing measurements silently.',
  ].join('\n');
}

function formatNumber(value: number): string {
  return Number(value.toFixed(4)).toString();
}

function formatPercent(value: number): string {
  return `${Number((value * 100).toFixed(2))}%`;
}
