import { GdwebDesignReference } from './gdweb-design-search.js';

export function buildDesignSpecContract(reference: GdwebDesignReference): string {
  const { design, images } = reference;
  const evidence = images
    .map(image => `${image.kind}=${image.width}x${image.height}`)
    .join(', ');

  return [
    '# GDWEB Design Specification Context',
    '',
    `- Schema: secret-mcp/design-index/v1`,
    `- Reference ID: gdweb-${design.strNo}`,
    `- Title: ${design.title}`,
    `- GDWEB URL: ${design.gdwebUrl}`,
    `- Registered date: ${design.registeredDate}`,
    `- Award: ${design.award || 'N/A'}`,
    `- Concept: ${design.concept || 'N/A'}`,
    `- Primary color: ${design.primaryColor || 'N/A'}`,
    `- Production company: ${design.productionCompany || 'N/A'}`,
    `- Visual evidence: ${evidence || 'unavailable'}`,
    '',
    '## Mandatory Next Action',
    '',
    `Inspect every attached evidence image and write one complete DESIGN_INDEX_gdweb-${design.strNo}.md document in the user's language.`,
    'Do not return a short mood-board summary. The document must be detailed enough that another LLM can implement a visually equivalent frontend without reopening GDWEB.',
    '',
    '## Evidence Rules',
    '',
    '- Mark every substantial statement as OBSERVED, INFERRED, or UNKNOWN.',
    '- OBSERVED means directly visible in an attached GDWEB screenshot or supplied metadata.',
    '- INFERRED means a reasonable implementation decision needed to recreate the visible result.',
    '- UNKNOWN means the screenshots do not reveal the behavior. Never present UNKNOWN behavior as fact.',
    '- Use numeric estimates for sizes, spacing, ratios, breakpoints, and timing. Avoid vague words such as large, modern, or spacious without measurable values.',
    '- Preserve layout hierarchy and visual relationships. Adapt copyrighted copy and brand assets unless the user explicitly owns or authorizes them.',
    '- Treat desktop and mobile screenshots as separate primary evidence. Explain every responsive transformation between them.',
    '',
    '## Required Document Structure',
    '',
    '### 1. Reconstruction Goal',
    '- Reference identity, intended visual fidelity, supported routes, target viewports, and explicit non-goals.',
    '',
    '### 2. Evidence Inventory',
    '- List every screenshot with its kind, dimensions, source URL, visible page range, and evidence limitations.',
    '',
    '### 3. Page Information Architecture',
    '- Ordered page outline from header to footer.',
    '- For every section include: section ID, semantic role, purpose, visible content, estimated height, background, container width, column model, alignment, overflow behavior, and mobile transformation.',
    '- Include a page-outline table that can be converted directly into component order.',
    '',
    '### 4. Section-Level Layout Specifications',
    '- Create one subsection for every visible page section.',
    '- Specify DOM hierarchy, grid/flex rules, max-width, gutters, padding, gap, aspect ratios, alignment, stacking, sticky/fixed behavior, and z-index relationships.',
    '- Record desktop and mobile values separately.',
    '',
    '### 5. Component Abstraction',
    '- Provide a complete component tree.',
    '- For every component define responsibility, reusable boundaries, props, variants, slots, local state, shared state, events, data dependencies, loading state, empty state, error state, and accessibility contract.',
    '- Distinguish page-specific composition from reusable primitives.',
    '',
    '### 6. Design Tokens',
    '- Provide machine-readable token tables for colors, typography, spacing, radii, borders, shadows, opacity, z-index, breakpoints, container widths, and motion durations/easings.',
    '- Assign stable token names and estimated concrete values.',
    '',
    '### 7. Typography System',
    '- Define font families or fallbacks, type scale, weight, line height, letter spacing, casing, text alignment, truncation, and responsive adjustments for every text role.',
    '',
    '### 8. Asset Manifest',
    '- Enumerate logos, photos, illustrations, icons, video, textures, and decorative media.',
    '- For each asset specify role, source evidence, crop, aspect ratio, focal point, responsive treatment, loading priority, object-fit behavior, and an acceptable replacement strategy.',
    '',
    '### 9. Responsive Specification',
    '- Define breakpoint behavior as rules, not only a list of viewport widths.',
    '- Document reflow, column collapse, content order, hidden/replaced elements, navigation changes, type changes, spacing changes, image crops, and touch-target requirements.',
    '',
    '### 10. Interaction and Motion',
    '- Define navigation, buttons, links, tabs, accordions, carousels, forms, hover/focus/pressed/disabled states, scroll behavior, sticky behavior, and transitions.',
    '- Mark screenshot-invisible behavior as INFERRED or UNKNOWN.',
    '',
    '### 11. Accessibility Requirements',
    '- Define landmarks, heading order, keyboard behavior, focus order, focus visibility, labels, alt text, contrast requirements, reduced-motion behavior, and minimum touch targets.',
    '',
    '### 12. Frontend Architecture',
    '- Specify routes, recommended directory structure, page modules, component modules, styling strategy, asset organization, data models, state ownership, server/client boundaries, and third-party library responsibilities.',
    '- Keep framework-specific decisions separate from visual requirements.',
    '',
    '### 13. Implementation Task Graph',
    '- Produce ordered implementation tasks with IDs, dependencies, inputs, outputs, affected components, completion criteria, and parallelizable groups.',
    '- Include foundation, tokens, primitives, sections, responsive work, interactions, accessibility, visual QA, and performance tasks.',
    '',
    '### 14. Acceptance Criteria',
    '- Define testable visual and behavioral checks for desktop and mobile.',
    '- Include screenshot comparison viewports, allowable geometry/color differences, overflow checks, text fitting, asset loading, keyboard checks, and performance expectations.',
    '',
    '### 15. Uncertainties and Decisions',
    '- List every UNKNOWN item and the implementation decision chosen in its place.',
    '- Keep assumptions explicit so a later LLM can revise them without rewriting the entire specification.',
    '',
    '## Completion Gate',
    '',
    'The DESIGN_INDEX document is incomplete unless another LLM can derive the page/component tree, tokens, responsive rules, assets, interactions, implementation order, and acceptance tests from the document alone.',
  ].join('\n');
}
